import fs from 'fs';
import path from 'path';

const map = {
    'ASTEROIDS': 'ASTEROID_CONFIG.COUNT',
    'ASTEROIDS_INIT_INNER': 'ASTEROID_CONFIG.INIT_INNER',
    'ASTEROIDS_INIT_OUTER': 'ASTEROID_CONFIG.INIT_OUTER',
    'ASTEROID_MAX_SIZE': 'ASTEROID_CONFIG.MAX_SIZE',
    'ASTEROID_MAX_SPEED': 'ASTEROID_CONFIG.MAX_SPEED',
    'ASTEROID_MIN_SIZE': 'ASTEROID_CONFIG.MIN_SIZE',
    'ASTEROID_SPLIT_OFFSET': 'ASTEROID_CONFIG.SPLIT_OFFSET',
    'BOUNDARY_CORRECTION_FORCE': 'BOUNDARY_CONFIG.CORRECTION_FORCE',
    'BOUNDARY_DAMPENING': 'BOUNDARY_CONFIG.DAMPENING',
    'BOUNDARY_TOLERANCE': 'BOUNDARY_CONFIG.TOLERANCE',
    'BOUNDARY_TOLERANCE_ROIDS': 'BOUNDARY_CONFIG.TOLERANCE_ROIDS',
    'PLANETS_LIMIT': 'PLANET_CONFIG.LIMIT',
    'PLANET_MAX_SIZE': 'PLANET_CONFIG.MAX_SIZE',
    'PLAYER_INITIAL_LIVES': 'PLAYER_CONFIG.INITIAL_LIVES',
    'PLAYER_RELOAD_TIME_MAX': 'PLAYER_CONFIG.RELOAD_TIME_MAX',
    'SHIPS_COMBAT_ORBIT_DISTANCE': 'SHIP_CONFIG.COMBAT_ORBIT_DISTANCE',
    'SHIPS_LIMIT': 'SHIP_CONFIG.LIMIT',
    'SHIPS_SEPARATION_DISTANCE': 'SHIP_CONFIG.SEPARATION_DISTANCE',
    'SHIPS_SPAWN_TIME': 'SHIP_CONFIG.SPAWN_TIME',
    'SHIP_BASE_MAX_SHIELD': 'SHIP_CONFIG.BASE_MAX_SHIELD',
    'SHIP_BULLET1_LIFETIME': 'SHIP_CONFIG.BULLET1_LIFETIME',
    'SHIP_BULLET2_LIFETIME': 'SHIP_CONFIG.BULLET2_LIFETIME',
    'SHIP_BULLET_FADE_FRAMES': 'SHIP_CONFIG.BULLET_FADE_FRAMES',
    'SHIP_BULLET_GRAVITY_FACTOR': 'SHIP_CONFIG.BULLET_GRAVITY_FACTOR',
    'SHIP_EVOLUTION_SCORE_STEP': 'SHIP_CONFIG.EVOLUTION_SCORE_STEP',
    'SHIP_FRIENDLY_BLUE_HUE': 'SHIP_CONFIG.FRIENDLY_BLUE_HUE',
    'SHIP_MAX_SPEED': 'SHIP_CONFIG.MAX_SPEED',
    'SHIP_RESISTANCE': 'SHIP_CONFIG.RESISTANCE',
    'SHIP_SIGHT_RANGE': 'SHIP_CONFIG.SIGHT_RANGE',
    'SHIP_SIZE': 'SHIP_CONFIG.SIZE',
    'SHIP_THRUST': 'SHIP_CONFIG.THRUST',
    'STATIONS_PER_PLANET': 'STATION_CONFIG.PER_PLANET',
    'STATIONS_SPAWN_TIMER': 'STATION_CONFIG.SPAWN_TIMER',
    'STATION_RESISTANCE': 'STATION_CONFIG.RESISTANCE'
};

const regexStr = '\\b(' + Object.keys(map).join('|') + ')\\b';
const regex = new RegExp(regexStr, 'g');

const jsModsDir = './js_modules';
const files = fs.readdirSync(jsModsDir).filter(f => f.endsWith('.js') && f !== 'config.js');

files.forEach(file => {
    let content = fs.readFileSync(path.join(jsModsDir, file), 'utf8');
    
    // First, fix the 'import ... from "./config.js";' line to be standard:
    content = content.replace(/import\s+\{.*\}\s+from\s+['"]\.\/config\.js['"];/g, 
    "import { ASTEROID_CONFIG, BOUNDARY_CONFIG, PLANET_CONFIG, PLAYER_CONFIG, SCORE_REWARDS, SHIP_CONFIG, STATION_CONFIG, FPS, FRICTION, G_CONST, MAX_Z_DEPTH, MIN_DURATION_TAP_TO_MOVE, SCALE_IN_MOUSE_MODE, SCALE_IN_TOUCH_MODE, WORLD_BOUNDS, ZOOM_LEVELS, suffixes, syllables, DOM } from './config.js';");
    
    // Replace all usages across the module body
    content = content.replace(regex, (match) => {
        return map[match];
    });

    fs.writeFileSync(path.join(jsModsDir, file), content, 'utf8');
    console.log('Processed', file);
});

